### PR TITLE
Create route groups

### PR DESCRIPTION
**Pull request by talyssonoc**
Implements proposal at #1262.

### CODE REVIEW

**Comment by talyssonoc** [comment]
I'm having a deprecation error (https://travis-ci.org/silexphp/Silex/jobs/83621808) with PHP 5.6 + SYMFONY_DEPS_VERSION=2.8:

```
Passing an instance of Symfony\Component\Validator\ValidatorInterface as argument to the Symfony\Component\Form\Extension\Validator\EventListener\ValidationListener::__construct method is deprecated since version 2.8 and will be removed in 3.0. Use an implementation of Symfony\Component\Validator\Validator\ValidatorInterface instead: 6x

    6x in ValidatorServiceProviderTest::testValidatorConstraint from Silex\Tests\Provider
```

**Comment by talyssonoc** [comment]
@fabpot @igorw do you know the possible cause for this?

**Comment by stof** [comment]
This looks weird to me. The service provider should be using the new validator implementation

**Comment by talyssonoc** [comment]
@stof Do you think it can be some sort of cache inside Travis?

**Comment by talyssonoc** [comment]
@fabpot, some comment about what could it be?

**Comment by talyssonoc** [comment]
@stof some ideia about it?

**Comment by stof** [comment]
@talyssonoc I suggest you to rebase your branch, which will retrigger a new Travis build. It may have been fixed by another change

**Pull request closed without merging**
