### PR TITLE
create logdir if not exists

### PR DESCRIPTION
**Pull request by dominikzogg**
Would be cool , if the provider guaranteed, that the log folder exists, where the logfile will be storred in.

### CODE REVIEW

**Comment by dominikzogg** [comment]
feedback from irc #silex-php

13:13:18 - theahindle: There are much more knowledgeable people than me, but I personally think it shouldn't change the file system in the background - it should be explicit
13:13:25 - steffkes: welcome in the nice world of php ..
13:13:43 - theahindle: Like setting the handler to Monolog\LoggerMakeDirOnMyBehalfPlease or setting $app['monolog.mkdir'] = true;
13:13:53 - steffkes: yeah i like that more as well theahindle.

**Comment by dominikzogg** [comment]
add an option is a valid solution for me, @fabpot what do you think?

**Comment by henrikbjorn** [comment]
In any case it should not be done in the definition of the service.

**Comment by dominikzogg** [comment]
@henrikbjorn Well what is your suggestion, close this PR and create one within monolog or handle it in my project(s)?

**Comment by henrikbjorn** [comment]
Yes. Monolog should do this inside the handler that writes to the filesystem. Until then, you should handle it in your projects.

On the code side of things. You are adding complexity through 3 new indentation levels and many more code paths.

**Comment by fabpot** [comment]
This is clearly the responsibility of Monolog to do that (if they want to, and they should :))

Regarding the option, that would not make sense. Asking someone to set an option to create a directory seems like the same amount of work than creating the directory directly. Closing this PR.

**Comment by dominikzogg** [comment]
@fabpot https://github.com/Seldaek/monolog/pull/584 should be solved

**Comment by fabpot** [comment]
@dominikzogg thanks for the heads up, that's a good news!

**Pull request closed without merging**
