### PR TITLE
Add createForm method to FormTrait.

### PR DESCRIPTION
**Pull request by fbourigault**
This allow to use Form Classes with ease.

```php
$form = $app->createForm(new UserType());
```

### CODE REVIEW

**Comment by fbourigault** [comment]
Waiting for #1085

**Comment by hkdobrev** [comment]
:+1:

**Comment by fbourigault** [comment]
I closed this PR because when rebasing I added lots of commit but I don't know how to avoid this. I opened a new one #1102.

PS : Docs about rebasing a PR without listing every commit in the branch is welcome.

**Comment by stof** [comment]
@fbourigault the issue is that you rebased on top of a different branch than the target of this PR

**Comment by fbourigault** [comment]
Ah right. I requested pull on the wrong branche !

**Pull request closed without merging**
