### PR TITLE
Validator translation domain is now customizable from service provider

### PR DESCRIPTION
**Pull request by CarsonF**
So the whole validator closure doesn't have to be rewritten to change it.

### CODE REVIEW

**Comment by stof** [comment]
What is the use case for changing it ? All builtin messages would then have to be translated again

**Comment by henrikbjorn** [comment]
I believe each field can have it changed when rendered or from the type options when adding the field.

**Comment by CarsonF** [comment]
I don't think it should be assumed which domain resources are add with. Those are able to be customized I think this should be as well. Maybe those should use this variable though.

**Comment by CarsonF** [comment]
All the builtin translation resources use the same variable now.

**Comment by fabpot** [comment]
But then again, it makes you re-translate all built-in messages. I don't see when it would be useful to change the default.

**Comment by CarsonF** [comment]
I guess I don't understand how it would make you re-translate the built-in messages? They would still be added the same way.

**Comment by stof** [comment]
@CarsonF but built-in translations are provided in the ``validators``. If you change the domain, you need to duplicate them in a different domain

**Comment by CarsonF** [comment]
Do you mean change it after creation? I don't intent to do that. Only override it when registering the service provider.

**Pull request closed without merging**
