### PR TITLE
decoupled the exception handler from HttpKernelServiceProvider

### PR DESCRIPTION
**Pull request by fabpot**

### CODE REVIEW

**Comment by henrikbjorn** [comment]
I am curious, what is the reasoning for doing this?

**Comment by fabpot** [comment]
Pure semantic. Same reasoning as for the other providers: they only do one thing and the exception handler has nothing to do with the other services of the provider.

**Comment by GromNaN** [comment]
:+1:

**Comment by stof** [comment]
:+1:

**Pull request merged**
