### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by nicoder**

### CODE REVIEW

**Comment by SpacePossum** [comment]
:+1:

**Comment by GromNaN** [comment]
You could have made only 1 PR for all #1283 and #1282.

**Comment by nicoder** [comment]
yes, with hindsight I would have, I guess I did not expect to find more.
Next time I should wait until I am done reading before sending the PRs, and juste send one if they are related.

**Comment by GromNaN** [comment]
You can (and should !) open a PR as soon as you find the first typo, but if you find another one just after you can add commits to the same branch, the PR will be automatically updated.

Regardless, thank you for fixing the doc.

**Comment by nicoder** [comment]
Oh, thanks, I hadn't thought about that, good idea.
I just clicked on 'Edit this' on the website and edited through the Github web UI,
which created a new branch every time.
I could've juste done that on the same branch on my fork in the web UI.

**Comment by fabpot** [comment]
Good catch, thanks @nicoder.

**Pull request closed without merging**
