### PR TITLE
changed the app variable in Twig to be an instance of Symfony AppVariable

### PR DESCRIPTION
**Pull request by fabpot**
That's more consistent with Symfony.

### CODE REVIEW

**Comment by fabpot** [comment]
And that's probably required for the web profiler.

**Comment by GromNaN** [comment]
Everywhere in Silex,  the app variable is the Silex\Application. Having something different with the same name in templates is inconsistent.

**Comment by stof** [comment]
@fabpot AFAIK, we tried hard to avoid relying on the ``app`` variable in the WebProfilerBundle (it was completely avoided at some point, but I think a feature added another usage again)

**Comment by jdreesen** [comment]
There is a bug in this implementation, because the `AppVariable` is in the `symfony/twig-bridge` which is not necessarily available.

I fixed it with a check for `class_exists('Symfony\Bridge\Twig\AppVariable')` but then I wasn't sure what the behaviour should be if `$app['twig.app_variable']` isn't available and if just falling back to `$twig->addGlobal('app', $app);` would be right, because there would be different behaviour depending on if the twig bridge is loaded or not. Maybe it's okay if we tell people in the documentation, but I don't know if it would be too confusing? This is why I sent no pull request for now.

**Pull request merged**
