### PR TITLE
[WIP/RFC] Route with conditional (by expression language) support on 1.x branch

### PR DESCRIPTION
**Pull request by SpacePossum**
proves the problem described here
https://github.com/silexphp/Silex/issues/1013#issuecomment-206963327

this test does pass on master

### CODE REVIEW

**Comment by GromNaN** [comment]
Thanks for the test case.
Your issue is more a feature request than a bug report. The expression engine component is currently not supported by Silex.

**Comment by SpacePossum** [comment]
Thanks @GromNaN, do you know if the support for the expressions in routes on master by design or (more or less) by accident?

**Comment by GromNaN** [comment]
After checking at the actual issue, it seems that the ExpressionLanguage component is automatically available in Routing : https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Routing/Matcher/UrlMatcher.php#L240-L250

But the request object is not accessible because Silex 1.x uses the [`UrlMatcher`](https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/Routing/Matcher/UrlMatcher.php#L88-L99). The [`RequestMatcher`](https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/Routing/Matcher/UrlMatcher.php#L104-L113) must be used to have this feature. The great news is that it is supported in Silex 2.x thanks to #971!

**Comment by GromNaN** [comment]
Also, for your use-case, you can user `requireHttps`.

```php
$app->get('/', function () { return 'test'; })->requireHttps();
```

**Comment by anasofiapaixao** [comment]
For anyone coming here via google looking for a workaround, although the `request` object is not available via Silex, the `context` object (of class `Symfony\Component\Routing\RequestContext`) is, which has some information that may be useful (like host, port, etc). For my use case,

``` context.getHost() === 'example.com' ```

did the trick.

**Comment by fabpot** [comment]
see #1334 for proper support in 2.0.

**Pull request closed without merging**
