### PR TITLE
Remove dependency on Silex\Application from Silex\Api\*

### PR DESCRIPTION
**Pull request by Seldaek**
This allows a CLI Cilex\Application to boot Silex providers.

### CODE REVIEW

**Comment by fabpot** [comment]
That does not work. `boot()` is tied with Silex and we should be able to use `Silex\Application` methods. Discussion happened back then and that's the compromise we found.

**Comment by Seldaek** [comment]
OK so the right thing in Cilex would be to skip booting those providers I guess? Or rather extend the Silex\Application? I'm looking for the best way to fix this..

**Comment by fabpot** [comment]
`boot()` is not used that much and IIRC, never needed for Cilex.

**Comment by Seldaek** [comment]
Ok I'll PR that then, thanks

**Pull request closed without merging**
