### PR TITLE
Security docs 1084

### PR DESCRIPTION
**Pull request by yamiko-ninja**
Adding some docs to clarify that the ``Silex\Application\SecurityTrait`` is for a user defined route and not the application to prevent issues like  #1084

### CODE REVIEW

**Comment by stof** [comment]
Why is there an article about profiling in this PR ?

**Comment by yamiko-ninja** [comment]
I must of made a commit to this branch by mistake while working on profile docs. Ill remove the file.

**Comment by yamiko-ninja** [comment]
Removed the article.

**Comment by fabpot** [comment]
merged in e7f1b4a577b3df94c7b8d9b966de56e121cde8c3
Thanks.

**Pull request closed without merging**
