### PR TITLE
symfony/security 2.7 as minimum version

### PR DESCRIPTION
**Pull request by Atriedes**
SecurityServiceProvider already use symfony/security 2.7

https://github.com/silexphp/Silex/blob/master/src/Silex/Provider/SecurityServiceProvider.php#L354

### CODE REVIEW

**Comment by stof** [comment]
The TokenStorage is alvailable in Symfony 2.6

**Comment by Atriedes** [comment]
there are different constructor in security v2.6 and v2.7

for 2.6 : https://github.com/symfony/Security/blob/2.6/Http/Firewall/ContextListener.php#L42

and for 2.7 : https://github.com/symfony/Security/blob/2.7/Http/Firewall/ContextListener.php#L43

and current silex SecurityProvider it use 2.7 for createing ContextListener

**Comment by Atriedes** [comment]
related issue : #1146

**Comment by J7mbo** [comment]
Thanks for championing this @Atriedes :-)

**Comment by J7mbo** [comment]
I just moved from composer's symfony/security @2.6.6 to `"symfony/security": "2.7.x-dev",` and this is working for me. I'm sorry if I seemed like I was trying to push your dev cycle up, I wasn't... just wanted to know how to get it working...

I'll not be patient and wait until this is updated to use 2.7 :-)

**Comment by fabpot** [comment]
I suppose that the problem is the same on 1.3, right?

**Comment by Atriedes** [comment]
@fabpot : yes it affect 1.3 too
https://github.com/silexphp/Silex/blob/1.3/src/Silex/Provider/SecurityServiceProvider.php#L357

It already follow 2.7 API

btw fapbot, could you please show what do you plan on v1.3 and v2

**Comment by fabpot** [comment]
Unfortunately, I'm not able to reproduce the error. If you read the code, you can see that for 2.6, the `security.token_storage` service is an alias for `security.context`, so this should work on both 2.6 and 2.7 without any change on 1.3 and master. Actually, tests pass and they do exercise this part of the code. So, there is something else going on.

Can you copy/paste the output of `composer show -i`?

**Comment by Atriedes** [comment]
Here is my output:

~~~
cnam/security-jwt-service-provider       0.0.6              Service Provider for usage jwt token for auth
dflydev/doctrine-orm-service-provider    v2.0.0             Doctrine ORM Service Provider
doctrine/annotations                     v1.2.4             Docblock Annotations Parser
doctrine/cache                           v1.4.1             Caching library offering an object-oriented API for many cache backends
doctrine/collections                     v1.3.0             Collections Abstraction library
doctrine/common                          v2.5.0             Common Library for Doctrine projects
doctrine/dbal                            v2.5.1             Database Abstraction Layer
doctrine/inflector                       v1.0.1             Common String Manipulations with regard to casing and singular/plural rules.
doctrine/instantiator                    1.0.4              A small, lightweight utility to instantiate objects in PHP without invoking their constr...
doctrine/lexer                           v1.0.1             Base library for a lexer that can be used in Top-Down, Recursive Descent Parsers.
doctrine/orm                             v2.5.0             Object-Relational-Mapper for PHP
firebase/php-jwt                         1.0.0              A simple library to encode and decode JSON Web Tokens (JWT) in PHP. Should conform to th...
jowy/silex-config-service-provider       v1.0.1             Silex Config Service Provider
jowy/silex-fractal-service-provider      v1.0.1             Silex Fractal Service Provider
jowy/silex-pimple-aware-event-dispatcher v1.0.0             Silex Pimple Aware Symfony Event Dispatcher
jowy/tactician-service-provider          v1.0.4             Silex tactician service provider
league/fractal                           0.12.0             Handle the output of complex data structures ready for API output.
league/tactician                         v0.5.0             A small, flexible command bus. Handy for building service layers.
monolog/monolog                          1.13.1             Sends your logs to files, sockets, inboxes, databases and various web services
pimple/pimple                            v3.0.0             Pimple is a simple Dependency Injection Container for PHP 5.3
psr/log                                  1.0.0              Common interface for logging libraries
silex/silex                              dev-master ba3bbef The PHP micro-framework based on the Symfony2 Components
swiftmailer/swiftmailer                  v5.4.0             Swiftmailer, free feature-rich PHP mailer
symfony/console                          v2.6.6             Symfony Console Component
symfony/debug                            v2.6.6             Symfony Debug Component
symfony/event-dispatcher                 v2.6.6             Symfony EventDispatcher Component
symfony/http-foundation                  v2.6.6             Symfony HttpFoundation Component
symfony/http-kernel                      v2.6.6             Symfony HttpKernel Component
symfony/routing                          v2.6.6             Symfony Routing Component
symfony/security                         v2.6.6             Symfony Security Component
symfony/translation                      v2.6.6             Symfony Translation Component
symfony/validator                        v2.6.6             Symfony Validator Component
symfony/yaml                             v2.6.6             Symfony Yaml Component
~~~

the error itself quite simple actually

~~~
Argument 1 passed to Symfony\Component\Security\Http\Firewall\ContextListener::__construct() must be an instance of Symfony\Component\Security\Core\SecurityContextInterface, instance of Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorage given, called in /home/jowy/Project/pras/singo-dev/vendor/silex/silex/src/Silex/Provider/SecurityServiceProvider.php on line 359 and defined
~~~

in 2.6 ContextListener require ` Symfony\Component\Security\Core\SecurityContextInterface` but in 2.7 it require `Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorage`. SecurityServiceProvider in 1.3 and master branch already follow 2.7 API but in composer.json still require <= 2.6

**Comment by fabpot** [comment]
As I explained above, we are compatible with both signatures. In 2.6, the token storage service is actually the same as the context one. So, I still don't see how that cannot work for you. Can you try to create the smallest script that reproduces the error?

**Comment by Atriedes** [comment]
~~~php
<?php

require "vendor/autoload.php";

$app = new \Silex\Application();

$app['security.firewalls'] = array(
    'admin' => array(
        'pattern' => '^/admin',
        'http' => true,
        'users' => array(
            // raw password is foo
            'admin' => array('ROLE_ADMIN', '5FZ2Z8QIkA7UTZ4BYkoC+GsReLf569mSKDsfods6LYQ8t+a8EW9oaircfMpmaLbPBh4FOBiiFyLfuZmTSUwzZg=='),
        ),
    ),
);

$app->register(new \Silex\Provider\SecurityServiceProvider());

$app->get("/admin/index",
    function (\Symfony\Component\HttpFoundation\Request $request) {
        $response = new \Symfony\Component\HttpFoundation\Response();

        $response->setContent("hello world from admin");

        return $response;
    }
);

$request = \Symfony\Component\HttpFoundation\Request::create("admin/index");

$app->run($request);
~~~

composer show -i

~~~
pimple/pimple            v3.0.0             Pimple is a simple Dependency Injection Container for PHP 5.3
psr/log                  1.0.0              Common interface for logging libraries
silex/silex              dev-master ba3bbef The PHP micro-framework based on the Symfony2 Components
symfony/debug            v2.6.6             Symfony Debug Component
symfony/event-dispatcher v2.6.6             Symfony EventDispatcher Component
symfony/http-foundation  v2.6.6             Symfony HttpFoundation Component
symfony/http-kernel      v2.6.6             Symfony HttpKernel Component
symfony/routing          v2.6.6             Symfony Routing Component
symfony/security         v2.6.6             Symfony Security Component
~~~

error stack trace

~~~
PHP Catchable fatal error:  Argument 1 passed to Symfony\Component\Security\Http\Firewall\ContextListener::__construct() must be an instance of Symfony\Component\Security\Core\SecurityContextInterface, instance of Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorage given, called in /home/jowy/Project/pras/slx/vendor/silex/silex/src/Silex/Provider/SecurityServiceProvider.php on line 359 and defined in /home/jowy/Project/pras/slx/vendor/symfony/security/Symfony/Component/Security/Http/Firewall/ContextListener.php on line 42
PHP Stack trace:
PHP   1. {main}() /home/jowy/Project/pras/slx/silex.php:0
PHP   2. Silex\Application->run($request = *uninitialized*) /home/jowy/Project/pras/slx/silex.php:32
PHP   3. Silex\Application->handle($request = *uninitialized*, $type = *uninitialized*, $catch = *uninitialized*) /home/jowy/Project/pras/slx/vendor/silex/silex/src/Silex/Application.php:489
PHP   4. Silex\Application->boot() /home/jowy/Project/pras/slx/vendor/silex/silex/src/Silex/Application.php:503
PHP   5. Silex\Provider\SecurityServiceProvider->subscribe($app = *uninitialized*, $dispatcher = *uninitialized*) /home/jowy/Project/pras/slx/vendor/silex/silex/src/Silex/Application.php:151
PHP   6. Pimple\Container->offsetGet($id = *uninitialized*) /home/jowy/Project/pras/slx/vendor/silex/silex/src/Silex/Application.php:567
PHP   7. Silex\Provider\SecurityServiceProvider->Silex\Provider\{closure}($app = *uninitialized*) /home/jowy/Project/pras/slx/vendor/pimple/pimple/src/Pimple/Container.php:112
PHP   8. Pimple\Container->offsetGet($id = *uninitialized*) /home/jowy/Project/pras/slx/vendor/pimple/pimple/src/Pimple/Container.php:127
PHP   9. Silex\Provider\SecurityServiceProvider->Silex\Provider\{closure}($app = *uninitialized*) /home/jowy/Project/pras/slx/vendor/pimple/pimple/src/Pimple/Container.php:112
PHP  10. array_map(*uninitialized*, *uninitialized*) /home/jowy/Project/pras/slx/vendor/silex/silex/src/Silex/Provider/SecurityServiceProvider.php:286
PHP  11. Silex\Provider\SecurityServiceProvider->Silex\Provider\{closure}($listenerId = *uninitialized*) /home/jowy/Project/pras/slx/vendor/silex/silex/src/Silex/Provider/SecurityServiceProvider.php:286
PHP  12. Pimple\Container->offsetGet($id = *uninitialized*) /home/jowy/Project/pras/slx/vendor/silex/silex/src/Silex/Provider/SecurityServiceProvider.php:274
PHP  13. Silex\Provider\SecurityServiceProvider->Silex\Provider\{closure}(*uninitialized*) /home/jowy/Project/pras/slx/vendor/pimple/pimple/src/Pimple/Container.php:112
PHP  14. Symfony\Component\Security\Http\Firewall\ContextListener->__construct($context = *uninitialized*, $userProviders = *uninitialized*, $contextKey = *uninitialized*, $logger = *uninitialized*, $dispatcher = *uninitialized*) /home/jowy/Project/pras/slx/vendor/silex/silex/src/Silex/Provider/SecurityServiceProvider.php:359
~~~

**Comment by fabpot** [comment]
So, the problem is only for master as this code works fine on 1.3. #1148 should fix the problem, can you confirm?

**Comment by Atriedes** [comment]
Yep thats working from my end

**Pull request closed without merging**
