### PR TITLE
The app.user does not work

### PR DESCRIPTION
**Pull request by harikt**
I changed it to `app.security.token` to make that work. See http://stackoverflow.com/questions/27958923/silex-the-token-storage-contains-no-authentication-token

### CODE REVIEW

**Comment by davedevelopment** [comment]
I think there might be another problem there, there should be an anonymous token at the very least? If you want to use `is_granted` etc, you need to be behind a firewall.

**Comment by harikt** [comment]
@davedevelopment I am really new to security component. Have been spending more time figuring out the issue. Seems 5 hours :-/ . At-least this worked for me. I have tried `app.user`, but it gave me a different error saying no user.

**Comment by davedevelopment** [comment]
@harikt drop in to #silex-php and I'll help you :)

**Comment by harikt** [comment]
Closing the PR .

**Pull request closed without merging**
