### PR TITLE
added sender_address to switfmailer provider

### LINKED ISSUE #1022: SwiftmailerServiceProvider.php - Add default sender-address option
'sender_address' => 'noreply@...'

http://symfony.com/doc/current/reference/configuration/swiftmailer.html#sender-address

### PR DESCRIPTION
**Pull request by fabpot**
fixes #1022

### CODE REVIEW

**Comment by stof** [comment]
:+1:

**Comment by stof** [comment]
btw, you should use your own fork to send PRs (as you do on Symfony) rather than the organization repo

**Comment by fabpot** [comment]
@stof oops, my mistake.

**Comment by danicomas** [comment]
nice!

**Pull request merged**
