### PR TITLE
Update fastcgi_pass socket location

### PR DESCRIPTION
**Pull request by victorhaggqvist**
This makes it correspond with ubuntu 14.04 defaults

### CODE REVIEW

**Comment by fabpot** [comment]
But then, what about other versions? I think we should keep both paths and add a comment about which distrib is using what.

**Comment by victorhaggqvist** [comment]
That is likely a good idea. From what I could catch online the one present atm,  `unix:/var/run/php-fpm/www.sock`, would be the CentOS default, right?

**Comment by victorhaggqvist** [comment]
Maybe something like that. Don't know which one would be better as the default uncommented, but did set it as ubuntu now.

**Comment by fabpot** [comment]
Thank you @victorhaggqvist.

**Pull request closed without merging**
