### PR TITLE
Route groups

### PR DESCRIPTION
**Pull request by talyssonoc**
Solves the proposed implementation at https://github.com/silexphp/Silex/issues/1262

### CODE REVIEW

**Comment by talyssonoc** [comment]
@fabpot Finally! After a lot of errors with merge (I've forgot I created the branch from `1.3`, so when I tried to merge with `master` I got a lot of conflicts and extra files... twice)

**Comment by fabpot** [comment]
@talyssonoc Thanks for your work on this. Several quick comments:

 * we should also have some docs about this new feature
 * as this is a new feature, it should be based on the master branch, not 1.3 (sorry about that)
 * I'm not sure about the `group` name (it was not obvious for me what it refers to)

**Comment by ragboyjr** [comment]
@talyssonoc, @fabpot, what if instead of using the word `group`, we just overload the `mount` function. This works exactly like mount does, we'd just let it take in a function as well.

```php
$app->mount('/api', function ($api) use ($app) {
    // Admin group
    $api->mount('/admin', function ($admin) use ($app) {
        // Get book with ID
        $admin->get('/books/:id', function ($id) use ($app) {
            // Update book identified by $id.
        });

        // Update book with ID
        $admin->put('/books/:id', function ($id) use ($app) {
            // Update book identified by $id.
        });

        // Delete book with ID
        $admin->delete('/books/:id', function ($id) use ($app) {
            // Update book identified by $id.
        });
    });
});
```

**Comment by fabpot** [comment]
@ragboyjr Looks like a fantastic idea!

**Comment by ragboyjr** [comment]
@talyssonoc, do you plan on making those changes, or should I make a separate PR?

**Comment by fabpot** [comment]
Closing as #1345 looks better to me.

**Pull request closed without merging**
