### PR TITLE
Disable xdebug on travis

### PR DESCRIPTION
**Pull request by romainneutron**

### CODE REVIEW

**Comment by GromNaN** [comment]
Can you give some reasons for disabling Xdebug?

**Comment by hkdobrev** [comment]
@GromNaN It improved the speed of tools like Composer, PHPUnit, PHP CS Fixer. Since it's not used for code coverage or benchmark profiling it could be disabled. See https://github.com/travis-ci/travis-ci/issues/5780

**Comment by romainneutron** [comment]
It uses resources for no benefit

**Comment by fabpot** [comment]
Thank you @romainneutron.

**Comment by GromNaN** [comment]
Thanks @hkdobrev and @romainneutron

**Pull request closed without merging**
